const MAKE_REQUEST_PLAYER_INFO = 'MAKE_REQUEST_PLAYER_INFO'
const GET_PLAYER_INFO = 'GET_PLAYER_INFO'
const ERROR_PLAYER_INFO = 'ERROR_PLAYER_INFO'

export { MAKE_REQUEST_PLAYER_INFO, GET_PLAYER_INFO, ERROR_PLAYER_INFO }
