const PLAYER_INFO_REQUEST = 'PLAYER_INFO_REQUEST'
const PLAYER_INFO_SUCCESS = 'PLAYER_INFO_SUCCESS'
const PLAYER_INFO_ERROR = 'PLEYER_INFO_ERROR'

const PLAYER_PERSONAL_DATA_REQUEST = 'PLAYER_PERSONAL_DATA_REQUEST'
const PLAYER_PERSONAL_DATA_SUCCESS = 'PLAYER_PERSONAL_DATA_SUCCESS'
const PLAYER_PERSONAL_DATA_ERROR = 'PLAYER_PERSONAL_DATA_ERROR'

const PLAYER_VEHICLES_REQUEST = 'PLAYER_VEHICLES_REQUEST'
const PLAYER_VEHICLES_SUCCESS = 'PLAYER_VEHICLES_SUCCESS'
const PLAYER_VEHICLES_ERROR = 'PLAYER_VEHICLES_ERROR'

const VEHICLES_ALL_REQUEST = 'VEHICLES_ALL_REQUEST'
const VEHICLES_ALL_SUCCESS = 'VEHICLES_ALL_SUCCESS'
const VEHICLES_ALL_ERROR = 'VEHICLES_ALL_ERROR'

const PLAYER_VEHICLE_STATS_REQUEST = 'PLAYER_VEHICLE_STATS_REQUEST'
const PLAYER_VEHICLE_STATS_SUCCESS = 'PLAYER_VEHICLE_STATS_SUCCESS'
const PLAYER_VEHICLE_STATS_ERROR = 'PLAYER_VEHICLE_STATS_ERROR'

export {
  PLAYER_INFO_REQUEST,
  PLAYER_INFO_SUCCESS,
  PLAYER_INFO_ERROR,
  PLAYER_PERSONAL_DATA_REQUEST,
  PLAYER_PERSONAL_DATA_SUCCESS,
  PLAYER_PERSONAL_DATA_ERROR,
  PLAYER_VEHICLES_REQUEST,
  PLAYER_VEHICLES_SUCCESS,
  PLAYER_VEHICLES_ERROR,
  PLAYER_VEHICLE_STATS_REQUEST,
  PLAYER_VEHICLE_STATS_SUCCESS,
  PLAYER_VEHICLE_STATS_ERROR,
  VEHICLES_ALL_REQUEST,
  VEHICLES_ALL_SUCCESS,
  VEHICLES_ALL_ERROR,
}
