const VEHICLES_ALL_REQUEST = 'VEHICLES_ALL_REQUEST'
const VEHICLES_ALL_SUCCESS = 'VEHICLES_ALL_SUCCESS'
const VEHICLES_ALL_ERROR = 'VEHICLES_ALL_ERROR'

const PLAYER_DATA_REQUEST = 'PLAYER_DATA_REQUEST'
const PLAYER_DATA_SUCCESS = 'PLAYER_DATA_SUCCESS'
const PLAYER_DATA_ERROR = 'PLEYER_DATA_ERROR'

export {
  VEHICLES_ALL_REQUEST,
  VEHICLES_ALL_SUCCESS,
  VEHICLES_ALL_ERROR,
  PLAYER_DATA_REQUEST,
  PLAYER_DATA_SUCCESS,
  PLAYER_DATA_ERROR,
}
